// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Task struct {
	ID        int64              `json:"id"`
	Type      int32              `json:"type"`
	Value     int32              `json:"value"`
	State     string             `json:"state"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
