// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package db

import (
	"context"
)

type Querier interface {
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	GetTasksCount(ctx context.Context) (int64, error)
	UpdateTaskState(ctx context.Context, arg UpdateTaskStateParams) error
}

var _ Querier = (*Queries)(nil)
