// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: query.sql

package db

import (
	"context"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
  type, value, state
) VALUES (
  $1, $2, $3
)
RETURNING id, type, value, state, created_at, updated_at
`

type CreateTaskParams struct {
	Type  int32  `json:"type"`
	Value int32  `json:"value"`
	State string `json:"state"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask, arg.Type, arg.Value, arg.State)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Value,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTasksCount = `-- name: GetTasksCount :one
SELECT COUNT(*) FROM tasks
`

func (q *Queries) GetTasksCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getTasksCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateTaskState = `-- name: UpdateTaskState :exec
UPDATE tasks
SET state = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateTaskStateParams struct {
	ID    int64  `json:"id"`
	State string `json:"state"`
}

func (q *Queries) UpdateTaskState(ctx context.Context, arg UpdateTaskStateParams) error {
	_, err := q.db.Exec(ctx, updateTaskState, arg.ID, arg.State)
	return err
}
